### ISSUE TITLE
手機呈現圖表單位會不見

### ISSUE THREAD

**Issue by jasjas110** [watchout-tw/olympus#14]
Android 的 ASUS Zenfone3 用 Chrome 開圖表單位會不見（如下圖）

![32564432_10155626840282914_891323091081232384_n](https://user-images.githubusercontent.com/26052751/40050135-2cc10e9e-5869-11e8-80e6-36d907bdddea.jpg)

@miajhaochen

**Comment by chihaoyo** [comment]
是說左邊y軸的數值和單位吧？

**Comment by chihaoyo** [comment]
看要不要只在y軸最上方顯示單位？把數值都顯示出來好像會很擠。

**Comment by chihaoyo** [comment]
1127fe1965c4e11b66bcfc3c2251099d21e4b751 暫時的解法：直接show出y軸
