### ISSUE TITLE
登出之後回到tsai-second-year已經畫好的資料會留著

### ISSUE THREAD

**Issue by chihaoyo** [watchout-tw/olympus#15]
1. 已經登入，在tsai-second-year頁面，已經畫完、送出了幾個圖表
2. 按下登出
3. 被導向首頁
4. 點《蔡總統的第二年》回到tsai-second-year頁面
5. 剛剛畫好的資料仍然看得到

有什麼想法嗎？

**Comment by miajhaochen** [comment]
畫完之後會把 point 的 show attribute 改掉
看起來是直接改到從require來的資料了
要deep clone~~~~

**Comment by chihaoyo** [comment]
✌️
