### ISSUE TITLE
Draw模組需要「我們會蒐集資料」的聲明

### ISSUE THREAD

**Issue by chihaoyo** [watchout-tw/olympus#16]
其中一個可以連結的是沃草共有地的[《使用條款》](https://documents.watchout.tw/watchout-commons/terms-of-service/)，也可以像《給問》一樣有一個[簡單版的條款](https://ask.watchout.tw/games/2018-taipei)。

**Comment by jasjas110** [comment]
這樣寫可以嗎~

除了「政府施政數據」，我們也關心「人民實際感受」，你在《畫畫看》所畫的每條線，都將成為沃草後續作品的原始資料。請靜待沃草後續作品出爐。

**Comment by chihaoyo** [comment]
超級沒有法律效力的感覺沒問題嗎？

**Comment by chihaoyo** [comment]
3380ebacf13f512b627234c01f2e24e9b9d1c695
