### ISSUE TITLE
蔡總統的第二年加入參考資料欄位

### ISSUE THREAD

**Issue by jasjas110** [watchout-tw/olympus#20]
@miajhaochen @chihaoyo 

參考資料
[內政部統計查詢網](http://statis.moi.gov.tw/micst/stmain.jsp?sys=100)
[中華民國統計資訊網](https://www.stat.gov.tw/mp.asp?mp=4)
[中華民國交通部觀光局](http://admin.taiwan.net.tw/public/public.aspx?no=315)
[台灣證券交易所](http://www.tse.com.tw/zh/statistics/statisticsList?type=07&subType=240)
[行政院環境保護署環境資源資料庫](https://erdb.epa.gov.tw/)
[台電系統歷年發電量](https://www.taipower.com.tw/tc/chart/a01_電力供需資訊_電源開發規劃_歷年發電量及結構.html)

**Comment by chihaoyo** [comment]
993d29d20c08b68a2305e658e509d5c99b317ae5
