### ISSUE TITLE
《蔡總統的第二年》圖表的順序變動

### ISSUE THREAD

**Issue by jasjas110** [watchout-tw/olympus#24]
因應給大統領的梗，520直播前十張圖的順序改成：
1. 失業率
2. 工時
3. 物價
4. 薪資
5. 出生人數
6. 來台旅客
7. 經濟成長率
8. 股市
9. 空汙
10. 發電

@chihaoyo

**Comment by chihaoyo** [comment]
62c35bb16b0a4c94a98d2bf7a9b274cab74fe52d

**Comment by chihaoyo** [comment]
未來可以在chart dataObject中指定`index`，只要全部的chart都有`index`，自動排序就會啟動。
